# Usa imagen oficial de Java
FROM openjdk:17-jdk-slim

# Copia el jar compilado al contenedor
COPY target/*.jar app.jar

# Expone el puerto 8080
EXPOSE 8080

# Comando para arrancar
ENTRYPOINT ["java","-jar","/app.jar"]

