# Usa la imagen oficial de OpenJDK
FROM openjdk:17-jdk-slim

# Copia el JAR compilado al contenedor
COPY target/*.jar app.jar

# Expone el puerto 8080
EXPOSE 8080

# Comando para arrancar
ENTRYPOINT ["java","-jar","/app.jar"]
